TABULAR_CLASSIFICATION = 1
IMAGE_CLASSIFICATION = 2
TABULAR_REGRESSION = 3
IMAGE_REGRESSION = 4
TIME_SERIES_CLASSIFICATION = 5
TIME_SERIES_REGRESSION = 6
TIME_SERIES_FORECASTING = 7

REGRESSION_TASKS = [TABULAR_REGRESSION, IMAGE_REGRESSION, TIME_SERIES_REGRESSION]
CLASSIFICATION_TASKS = [TABULAR_CLASSIFICATION, IMAGE_CLASSIFICATION, TIME_SERIES_CLASSIFICATION]
FORECASTING_TASKS = [TIME_SERIES_FORECASTING]

TASK_TYPES = REGRESSION_TASKS + CLASSIFICATION_TASKS + FORECASTING_TASKS

TASK_TYPES_TO_STRING = \
    {TABULAR_CLASSIFICATION: 'tabular_classification',
     IMAGE_CLASSIFICATION: 'image_classification',
     TABULAR_REGRESSION: 'tabular_regression',
     IMAGE_REGRESSION: 'image_regression',
     TIME_SERIES_REGRESSION: 'time_series_regression',
     TIME_SERIES_CLASSIFICATION: 'time_series_classification',
     TIME_SERIES_FORECASTING: 'time_series_forecasting'}

STRING_TO_TASK_TYPES = \
    {'tabular_classification': TABULAR_CLASSIFICATION,
     'image_classification': IMAGE_CLASSIFICATION,
     'tabular_regression': TABULAR_REGRESSION,
     'image_regression': IMAGE_REGRESSION,
     'time_series_regression': TIME_SERIES_REGRESSION,
     'time_series_classification': TIME_SERIES_CLASSIFICATION,
     'time_series_forecasting': TIME_SERIES_FORECASTING}

BINARY = 10
MUTLIOUTPUT = 11
MULTICLASS = 12
CONTINUOUS = 13

OUTPUT_TYPES = [BINARY, MUTLIOUTPUT, MULTICLASS, CONTINUOUS]

OUTPUT_TYPES_TO_STRING = \
    {BINARY: 'binary',
     MUTLIOUTPUT: 'multi-output',
     MULTICLASS: 'multi-class',
     CONTINUOUS: 'continuous'}

STRING_TO_OUTPUT_TYPES = \
    {'binary': BINARY,
     'multi-output': MUTLIOUTPUT,
     'multi-class': MULTICLASS,
     'continuous': CONTINUOUS}
